import { CodeType } from "@/common/schemas/request-mint-codes.schema";

export type CreatePoapInput = {
  event_id: string; // event id of the rendevu event we are creating the poap for
  city: string; // (optional for virtual)
  country: string; // (optional for virtual)
  description: string; // Description of the event
  email: string; // Email for mint links
  end_date: string; // End date (can be same as start)
  event_template_id?: number; //Template ID (default 0)
  event_url: string; // URL for the event (optional)
  expiry_date: string; // Expiry date for the POAP (optional)
  image: string | null; // Base64-encoded image or URL (500x500, <4MB, .png/.gif/.webp)
  name: string; // Name of the Drop
  notify_issuer: boolean; // Whether to notify the issuer (default true)
  private_event: boolean; // Whether the event is private (default false)
  year?: number; // Optional, default is 1
  requested_codes?: number; // Number of requested codes
  secret_code: string; // Secret code for the POAP
  start_date: string; // Start date of the event
  virtual_event: boolean;
};

export type UpdatePoapInput = {
  eventId: string; // event id of the rendevu event we are updating the poap for
  name: string;
  description: string;
  start_date: string;
  end_date: string;
  expiry_date: string;
  secret_code: string;
  city: string;
  country: string;
  event_url?: string;
  event_template_id?: number;
  virtual_event?: boolean; // defaults to false
  private_event?: boolean; // defaults to false
};

export type RequestMintCodesInput = {
  claim_name?: string;
  redeem_type: CodeType;
  secret_code: string;
  requested_codes: number;
};

export type Poap = {
  id: number; // Auto-generated by ORM
  createdAt: string; // ISO 8601 date string
  updatedAt: string; // ISO 8601 date string
  deletedAt?: string; // Optional, for soft delete
  eventId?: number; // Optional, if provided must be a valid event ID
  city?: string; // Optional, if virtual event
  country?: string; // Optional, if virtual event
  description: string; // Description of the event
  email: string; // Email for mint links
  end_date: string; // End date (can be same as start)
  event_template_id: number; // Template ID (default 0)
  event_url?: string; // URL for the event (optional)
  expiry_date?: string; // Expiry date for the POAP (optional)
  image: string; // Base64-encoded image or URL (500x500, <4MB, .png/.gif/.webp)
  name: string; // Name of the Drop
  notify_issuer: boolean; // Whether to notify the issuer (default true)
  private_event: boolean; // Whether the event is private (default false)
  requested_codes: number; // Number of requested codes
  secret_code: string; // Secret code for the POAP
  start_date: string; // Start date of the event
  virtual_event: boolean; // Whether the event is virtual
  year?: number; // Optional, default is 1
};
