// imports
import { Address } from "thirdweb";

export * from "./user.dto";

type DateString = string; // ISO 8601 date string

export type User = {
  id: number; // Auto-generated by ORM
  createdAt: DateString; // Auto-generated by ORM
  updatedAt: DateString; // Auto-generated by ORM
  deletedAt?: DateString; // Auto-generated by ORM, optional for soft delete
  walletAddress: Address; // Required, unique
  email: string; // Required, unique
  fullName: string; // Required
  username: string; // Required, unique
  avatar?: string; // Optional
  notificationsAllowed: boolean; // Required, defaults to true
};
